---
name: Build westerOS
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "42 6 * * 0"  # 6:42 UTC Sunday
    - cron: "42 6 * * 1,2,3,4,5,6"  # 6:42 UTC Monday-Saturday
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:
permissions:
  contents: write
  packages: write
  id-token: write
jobs:
  lint:
    name: Lint Project
    uses: ./.github/workflows/lint.yml
  build-image:
    name: Build Images
    needs: [lint]
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        image_flavor: ["desktop", "server"]
    with:
      image_flavor: ${{ matrix.image_flavor }}
  build-iso:
    name: Build ISOs
    uses: ./.github/workflows/build-iso.yml
    secrets: inherit
    needs: [build-image]
    strategy:
      fail-fast: false
      matrix:
        image_flavor: ["desktop"]
    with:
      image_flavor: ${{ matrix.image_flavor }}
  create-release:
    name: Create Release
    needs: [build-iso]
    uses: ./.github/workflows/create-release.yml
