---
name: Build westerOS ISOs
on:
  workflow_dispatch:
    inputs:
      image_flavor:
        description: "The image flavor to build, Make sure it matches"
        type: choice
        options:
          - "desktop"
        default: "desktop"
  workflow_call:
    inputs:
      image_flavor:
        type: string
        required: true
env:
  IMAGE_REGISTRY: ghcr.io/mariolopjr
  IMAGE_NAME: westeros
concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.ref
    || github.run_id }}-${{ inputs.image_flavor }}.iso
  cancel-in-progress: true
jobs:
  build-iso:
    name: Build ${{ inputs.image_flavor }} ISOs
    outputs:
      url: ${{ steps.url.outputs.url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - name: Maximize Build Space
        if: >-
          contains(fromJson('["workflow_dispatch", "workflow_call"]'),
          github.event_name) || github.event.schedule == '41 6 * * 0'
        uses: ublue-os/remove-unwanted-software@v8
      - name: Build ISO
        if: >-
          contains(fromJson('["workflow_dispatch", "workflow_call"]'),
          github.event_name) || github.event.schedule == '41 6 * * 0'
        shell: bash
        run: |
          sudo just build-iso ${{ inputs.image_flavor }} 1 1
          tree "./${{ env.IMAGE_NAME }}_build/output/"
      - name: Upload ISOs and Checksum to Job Artifacts
        id: upload
        uses: actions/upload-artifact@v4
        if: >-
          contains(fromJson('["workflow_dispatch", "workflow_call"]'),
          github.event_name) || github.event.schedule == '41 6 * * 0'
        with:
          name: ${{ inputs.image_flavor }}-iso
          path: |
            ./${{ env.IMAGE_NAME }}_build/output/
          if-no-files-found: warn
          retention-days: 0
          compression-level: 0
          overwrite: true
      - name: Make URL Artifact
        shell: bash
        id: url
        run: |
          case "${{ inputs.image_flavor }}" in
          "desktop")
            upload="stable"
            ;;
          esac
          echo "|[${{ inputs.image_flavor }}](${{ env.ARTIFACT-URL }})|" \
            > url-${upload}-${{ inputs.image_flavor }}.txt
          echo "url=${upload}" >> $GITHUB_OUTPUT
        env:
          ARTIFACT-URL: ${{ steps.upload.outputs.artifact-url }}
      - name: Upload ISO URL for Changelogs
        id: upload-url
        uses: actions/upload-artifact@v4
        with:
          name: url-${{ steps.url.outputs.url }}-${{ inputs.image_flavor }}
          path: url-${{ steps.url.outputs.url }}-${{ inputs.image_flavor }}.txt
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true
  changelogs:
    name: ${{ inputs.image_flavor }} Changelogs
    uses: ./.github/workflows/changelogs.yml
    secrets: inherit
    needs: build-iso
    with:
      target: ${{ needs.build-iso.outputs.url }}

