---
name: Lint Project
on:  # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Just
        id: just
        uses: ./.github/actions/install-just

      - name: Lint Project
        id: lint
        shell: bash
        run: |-
          just lint
